version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: colorstudy_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: colorstudy
      MYSQL_USER: m29user
      MYSQL_PASSWORD: m29Pa55word
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./colorstudy.sql:/docker-entrypoint-initdb.d/colorstudy.sql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: colorstudy_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data: